mount_path: "/calendar"
layout: 'dashboards'
monthNames: ['Январь','Февраль','Март','Апрель','Май','Июнь','Июль','Август','Сентябрь','Октябрь','Ноябрь','Декабрь']
monthNamesShort: ['Янв.','Фев.','Март','Апр.','Май','Июнь','Июль','Авг.','Сент.','Окт.','Ноя.','Дек.']
dayNames: ['Воскресенье','Понедельник','Вторник','Среда','Четверг','Пятница','Суббота']
dayNamesShort: ['ВС','ПН','ВТ','СР','ЧТ','ПТ','СБ']
buttonText: {
  prev: 'Предыдущий',
  next: 'Следующий',
  today: "Сегодня",
  month: "Месяц",
  week: "Неделя",
  day: "День"
}
axisFormat: 'HH:mm'
dragOpacity: {
  agenda: '.5'
}
slotMinutes: 15
timeFormat: 'H:mm'
displayEventEnd: true
